### ISSUE TITLE
Internationalized Resource Identifier (IRI) Standardization

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Ontology#10]
The ontology draft presently contains IRI's that are text-based using the CEDS element names and option set codes:

Example: http://ceds.ed.gov/owl#EnglishLearnerStatus (This is a Class)
Example: http://ceds.ed.gov/owl#EnglishLearnerStatus_Yes (This is an Individual)

The IRI's are identifiers intended to last "forever" that point to that element and option set. In CEDS for elements, we also have a concept of Global Id which is a numeric identifier that is associated with an element and spans all versions. We also have the concept of a Term Id which is numeric and is version specific.

We would like some feedback related to whether or not we should use text "EnglishLearnerStatus" in the IRI or instead use the numeric id such as Global ID: 000180 (The Global ID for English Learner Status).

Instead of this:
Example: http://ceds.ed.gov/owl#EnglishLearnerStatus (This is a Class)
Example: http://ceds.ed.gov/owl#EnglishLearnerStatus_Yes (This is an Individual)
We do this:
Example: http://ceds.ed.gov/owl#000180 (This is a Class)
Example: http://ceds.ed.gov/owl#000180 _Yes (This is an Individual)

They "why" - in the past, the term Limited English Proficient was used. That term ceased to be used in favor of using English Learner. In the Ontology, a change like that may require a new IRI. Would Limited English Proficient cease to be used? Are we renaming the same thing or are we talking about something definitionally different. Now English Learner is just an example, so we are not asking about that change, but using that as an example.

CEDS does not have numeric values for it's option set enumerations, but should we develop them for the ontology? Should those be used in place of the code value?

Current Draft:
Example: http://ceds.ed.gov/owl#EnglishLearnerStatus_Yes (This is an Individual)
With Global Id, but text value enumeration:
Example: http://ceds.ed.gov/owl#000180 _Yes (This is an Individual)
With all numeric values:
Example: http://ceds.ed.gov/owl#00018000001 (This is an Individual) (Note the number is a concatenation of the six digit Global Id (000180) and a five digit number we can assign to an option (00001). By concatenating with the Global Id, we end up with a unique option set number and can reuse the 00001 in other enumerations.

There's not necessarily a right or wrong answer to this, but we are gathering opinions and use cases since this is such a foundational part of the ontology.

**Comment by philbarker** [comment]
You make the correct case for doing this, on its own it is quite compelling. The case against is the lack of human readability, so if you do go with opaque identifiers then you should ensure that there is good support for humans using the ontology. 

For example Wikidata uses opaque identifiers for the reasons you suggest (it is very multilingual and preferred labels can change frequently) but the query and data editing interface allows you to put in words (e.g. name) and will show a drop-down list of labels for candidate properties/classes; so I can build a sparql [query](https://query.wikidata.org/querybuilder/?uselang=en) to find people with a certain given name without knowing that the property for given name is P735 and the value I searched for is a subClass of Q19685923.  I think that without such support wikidata would be unusable.

**Comment by stuartasutton** [comment]
I agree with Phil that your case is compelling. I have never found the human readability of identifiers argument to hold much water since there should be no need for end-user-humans to decipher an IRI identifier.  The meaning of a term should be based on a well defined definition and not on some label concatenated onto a namespace IRI.   Opaque identifiers are useful in the contexts identified by both Duane and Phil: (1) where particular labels may (and do) become disfavored; and (2) where multilinguality is needed and where giving preference to any single language in crafting semantic IRIs is inappropriate.  That said, Phil is absolutely correct that opaque identifiers require additional infrastructure in serving end-user-humans.

**Comment by stuartasutton** [comment]
@AEMDuaneBrown, while this may be a step too far given needs to align with existing CEDS identifier practices, did you consider going totally opaque with IRIs; i.e., simply concatenating the namespace with UUIDs for both properties, classes and individual (e.g., http://ceds.ed.gov/owl#7d75ab7c-49c4-41a7-9c14-07b9ea0da0f5)?

**Comment by philbarker** [comment]
@stuartasutton definitely a step too far. GUIDs are designed to be unique on their own if everyone on the planet uses them; the use of a web domain prefix means that not everyone on the planet will be using this scheme.

**Comment by 4pins** [comment]
Stuart:

Also CEDS drives a lot of mappings.  If we can reuse the existing
identifiers, things are significantly simpler for multiple groups.

Hopeful,

*John W. Lovell*

Technology Director

*Access 4 Learning (A4L) Community*

*Connecting and Securing Effective Learning Ecosystems ®*

https://www.A4L.org <https://www.a4l.org/>



*Join us at the pK20W+ Privacy & Interoperability Summit - November 7-9,
2023*: https://home.a4l.org/privacy-interoperability-summit-2023/


*PLEASE NOTE:  **From January 2022, your A4L-SDPC Community login username
has been changed to the email address associated with your User Profile.*
*Forgot your Community password?*  Reset it here:
*https://www.A4L.org/general/email_pass.asp*
<https://www.a4l.org/general/email_pass.asp>

**Comment by aemnathanclinton** [comment]
A standard has been reached.  Closing this ticket.
