### ISSUE TITLE
Future development of the CEDs Owl and its namespace policy

### ISSUE THREAD

**Issue by stuartasutton** [CEDStandards/CEDS-Ontology#11]
Throughout much of the excellent webinar introducing the draft CEDS ontology, I was wondering about whether consideration has been given at this point to how the ontology namespace will develop going forward and based on what principles beyond OWL. Like other large (and some small) description languages such as schema.org, CTDL, and Dublin Core, CEDS is continuously evolving. Some of these languages have defined policies regarding the structure of URI/IRIs, guidance and constraints when changes are suggested or new terms added. These namespace policies turn out to be critical to the principled management of the languages over time. For example:

1. **CTDL**: https://credreg.net/page/namespacepolicy
2. **Dublin Core**: https://www.dublincore.org/specifications/dublin-core/dcmi-namespace/

While I realize that potential content of such a policy for a CEDS ontology namespace is still in early development, I nevertheless  wonder whether there are any current intensions to articulate and publish such a namespace policy.

**Comment by AEMDuaneBrown** [comment]
Great advice. I can see that CTDL and Dublin Core are using the persistent uniform resource locator (PURL.org). Are you aware of other ontology standards using that as a namespace standard? Any pros/cons for utilizing that standard versus going with a direct ceds.ed.gov?

**Comment by philbarker** [comment]
@AEMDuaneBrown CTDL also uses it. I (and I believe @stuartasutton ) would recommend you don't. You absolutely do need a strategy for persistent URLs, but running you own purl server would be better than using PURL.org which has been quite problematic.

**Comment by stuartasutton** [comment]
+1 to Phil. I recommend that you not use the public PURL.org service run by the Internet Archive.  If CEDS can **guarantee the integrity** of the namespace in "perpetuity" :-), there is no need for the redirection that services like PURL.org provide.

**Comment by aemnathanclinton** [comment]
We will be using http://ceds.ed.gov/terms# as the official namespace.
