### ISSUE TITLE
Domains may restrict property reuse

### ISSUE THREAD

**Issue by philbarker** [CEDStandards/CEDS-Ontology#14]
In many cases the declaration of a Domain for a property will restrict its use. For example not every use case demands that a person have more than one date of birth recorded, and for these use cases it would be natural for `ceds:BirthDate` to be used directly on a class of type `Person`; however the assertion that the domain of `ceds:BirthDate` is `ceds:PersonBirth` is only compatible with this if `ceds:PersonBirth` and `ceds:Person` are not disjoint classes. Is it OK for some `ceds:PersonBirth`s to also be `ceds:Person`s?

**Comment by aemnathanclinton** [comment]
Resolve in V12.0.0.0 release.
