### ISSUE TITLE
:GradesOffered_10 should be a :GradeLevel

### ISSUE THREAD

**Issue by philbarker** [CEDStandards/CEDS-Ontology#17]
around line 7509 of the ttl output:
```
:GradesOffered_10 rdf:type owl:NamedIndividual ;
```
should be
```
:GradesOffered_10 rdf:type owl:NamedIndividual ,
                          :GradeLevel ;
```

(This will remove :GradesOffered_10 from the Instances pane in Protege when looking at Individuals by class with no class selected.)

**Comment by aemnathanclinton** [comment]
Resolved in V12.0.0.0.
