### ISSUE TITLE
repeated dc:identifiers

### ISSUE THREAD

**Issue by philbarker** [CEDStandards/CEDS-Ontology#19]
An identifier is supposed to identify one thing, yet many times several individuals in the ontology have the same values for dc:identifier. I believe this happens with option sets mapped to a range, where the class and the individual members of that class all get the CEDS element ID as the dc:identifier

It would be better to use the CEDS element ID for the class and to create new ids for each class member.

You might also consider xsd:token or xsd:string as a type for the identifiers rather than xsd:integer: it will save arguments over whether the zero-padding is significant (is 001929 the same as 1929?).

**Comment by aemnathanclinton** [comment]
Resolved in V12.0.0.0 release.
