### ISSUE TITLE
PersonOtherName class is disjoint from its declared subclasses

### ISSUE THREAD

**Issue by johnmannpaul** [CEDStandards/CEDS-Ontology#22]
PersonOtherName is asserted to be disjoint from its subclasses (i.e. PersonOtherName_Alias, PersonOtherName_FullName, Person_OtherName_NickName, etc.) As a result these subclasses are inconsistent (i.e. provably equivalent to Nothing).

**Comment by philbarker** [comment]
Furthermore, PersonOtherName is disjoint from itself.

**Comment by aemnathanclinton** [comment]
No longer relevant with V12.0.0.0.
