### ISSUE TITLE
Intersections of disjoint sets in property ranges or domains makes for inconsistent properties

### ISSUE THREAD

**Issue by johnmannpaul** [CEDStandards/CEDS-Ontology#23]
The domains or ranges for several properties 

hasCourseIdentfication
hasLeadIdentification
hasSchoolIdentification
hasStateAgencyIdentification
isContactPublished

are specified as the intersection of multiple classes (e.g. isContactPublished specifies the intersection of ElectronicMailAddress, OrganizationTelephone, and PersonTelephone for the domain). As noted in #21 this is probably not what is intended, but when the classes involved are disjoint (e.g. as OrganizationTelephone and PersonTelephone) then this causes the associated range or domain to be inconsistent (i.e. provably equivalent to Nothing). Consequently the property itself is inconsistent (i.e. empty). 

The properties listed above all have this issue.

**Comment by 4pins** [comment]
@johnmannpaul Fair point.  Do you have a suggested solution?  I assume relationships that are fewer in number or clearer or some combination of the two?

**Comment by philbarker** [comment]
:RecordStartDateTime and :RecordEndDateTime are great examples of this: they both unite pretty much everything in their domain.

IMO, the best solution is either use abstract super-classes for the domain / range (similar to owl:Thing if it's widely used) and/or to have a more loosely defined vocabulary and use SHACL constraints to specify what data is expected for which applications.

**Comment by aemnathanclinton** [comment]
No longer relevant with V12.0.0.0.  Doman and Range are no longer used.  Schema.org's domainIncludes and rangeIncludes are used instead to loosely define the vocabulary.
