### ISSUE TITLE
PersonOtherName is a Class and Property

### ISSUE THREAD

**Issue by philbarker** [CEDStandards/CEDS-Ontology#26]
https://github.com/CEDStandards/CEDS-Ontology/blob/4320dc03a314629825b484ac22c9ebca077dc152/src/CEDS-CoreDraft.ttl#L2173-L2177

https://github.com/CEDStandards/CEDS-Ontology/blob/4320dc03a314629825b484ac22c9ebca077dc152/src/CEDS-CoreDraft.ttl#L3875-L3876

**Comment by aemnathanclinton** [comment]
This issue was resolved in the V1.0.0.0 release.
