### ISSUE TITLE
Using a compact URI for skos in <rdf:type rdf:resource="skos:ConceptScheme"/> seems to be an error

### ISSUE THREAD

**Issue by philbarker** [CEDStandards/CEDS-Ontology#32]
My RDF/XML isn't great, but it seems like you cannot use compact URIs as an XML attribute value: it doesn't translate to turtle properly.

I think you need the full IRI:
`<rdf:type rdf:resource="http://www.w3.org/2004/02/skos/core#ConceptScheme"/>`

(Needs fixing also for `skos:Concept` as a value for `rdf:type`)

**Comment by AEMDuaneBrown** [comment]
Corrected with Version 12.1.0.0. release
