### ISSUE TITLE
Datatypes section explicitly calls out only time as a datatype

### ISSUE THREAD

**Issue by AEMDuaneBrown** [CEDStandards/CEDS-Ontology#9]
The datatypes section of the RDF and TTL document only calls out "time" as a datatype. The other datatypes are referred to in the header by calling out "xmlns:xsd="http://www.w3.org/2001/XMLSchema#" which is then referenced in the Data Properties. But since "time" is also referred to through this IRI, it should be made consistent in the RDF file. Recommend removing the datatypes section unless a new datatype is created that cannot be referenced through another standard.

**Comment by aemnathanclinton** [comment]
No longer relevant with V12.0.0.0.
